import React from 'react';
import ReactDOM from 'react-dom';
// import { HookApp } from "./HookApp";
// import { CounterApp } from "./components/01-useState/CounterApp";
// import { CounterWithCustomHook } from "./components/01-useState/CounterWithCustomHook";
// import { SimpleForm } from "./components/02-useEffect/SimpleForm";
// import { FormWithCustomHook } from "./components/02-useEffect/FormWithCustomHook";
// import { MultipleCustomHook } from "./components/03-examples/MultipleCustomHook";
// import { FocusScreen } from "./components/04-useRef/FocusScreen";
// import { RealExampleRef } from './components/04-useRef/RealExampleRef';
// import { Layout } from './components/05-useLayoutEffect/Layout';
// import { Memorize } from './components/06-memos/Memorize';
// import { MemoHook } from './components/06-memos/MemoHook';
// import { CallbackHook } from './components/06-memos/CallbackHook';
// import { Padre } from './components/07-tarea-memo/Padre';
// import { Memorize } from './components/08-ejemplos-memorize/Memorize';
// import { TodoApp } from './components/09-useReducer/TodoApp';
import CounterApp from './components/10-useReducer-ejemplos/CounterApp';
// import TodoApp from './components/10-useReducer-ejemplos/TodoApp';
// import ProductApp from './components/10-useReducer-ejemplos/ProductApp';

ReactDOM.render(<CounterApp />, document.getElementById('root'));
